[project]
name = "itk_tasks"
version = "0.1.0"
description = "ITK practical tasks"
authors = [
    { name="Slava Kulikov" }
]
dependencies = [
    "ruff>=0.12.7",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
